name: GitHub Tag

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  check:
    name: Get Version and Check Tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    outputs:
      version: ${{ steps.get_version.outputs.version }}
      exists: ${{ steps.check.outputs.exists }}

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=version::$(cat ASDML.NET/ASDML.NET.csproj | sed -nE "s/[[:blank:]]*<Version>(.*)<\/Version>[[:blank:]]*/v\1/p")
    - name: Checks if tag exists
      id: check
      run: git tag --list | egrep -q "^${{ steps.get_version.outputs.version }}$" && echo ::set-output name=exists::true || echo ::set-output name=exists::false

  tag:
    name: Create GitHub Tag
    runs-on: ubuntu-latest
    needs: [ check ]
    if: github.event.pull_request.merged && !needs.check.outputs.exists

    steps:
    - uses: actions/checkout@v2
    - name: Push Tag to GitHub
      uses: tvdias/github-tagger@v0.0.2
      env:
        repo-token: $${{ secrets.GITHUB_TOKEN }}
        tag: ${{ needs.check.outputs.version }}
